### ISSUE TITLE
Actividad 7, Linea del tiempo, Edgar Fabian castro Pérez

### ISSUE THREAD

**Issue by 11042002** [SistemasTecTlaxiaco/actividad-7-11042002#1]
![1](https://user-images.githubusercontent.com/72110043/196262277-f498601f-2c11-4d58-a92e-fdfe5b3395bd.png)
![2](https://user-images.githubusercontent.com/72110043/196262281-606b83f2-7ed5-4e47-b567-5eb275eb6ae2.png)
![3](https://user-images.githubusercontent.com/72110043/196262285-6617f249-a52f-4114-b6e4-849cf1ad9cc8.png)
![4](https://user-images.githubusercontent.com/72110043/196262288-b0bea421-3860-4c6a-b4a9-08b902b9012a.png)

**Comment by Jaczibeth** [comment]
del 20% obtuviste un 19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
